import random

class Level:
    """
    generate new level by the size given
    level_num --> int
    """
    def __init__(self, xtile, ytile):
         self.tile_list = [[0] * xtile for i in range(ytile)]
    
    def get_levelnumber(self):
        """print the level number"""
        print(self.level_num)

    def get_floorplan(self):
        """return the level generated"""
        return self.tile_list


class Tile:
    """
    distribute the various characters and items into the different tiles in the level
    tile_list --> list generated by level class
    monster_list --> list generated by monster class(tbc)
    item_list --> list generated by item lclass(tbc)
    
    """
    def __init__(self, tile_list, monster_list, item_list):
        self.tile_list = tile_list
        self.monster_list = monster_list
        self.item_list = item_list

    def spawn_monsters(self, monster_name):
        """
        randomly add monster into tiles
        """
        
        for monster in monster_list:
            #set posotion of monster
            
            

    def add_items(self, data):
        """
       randomly add items into tiles
       """
        pass

    def display(self, tile_number):
        print()