import random

class Level:
    """
    generate new level by the size given
    level_num --> int
    """
    def __init__(self, tile_list):
         self.tile_list = tile_list
    
    def get_levelnumber(self):
        """print the level number"""
        print(self.level_num)

    def get_floorplan(self):
        """return the level generated"""
        return self.tile_list

    def spawn_monster(self, monster_name,):
        """
        randomly add monster into tiles
        """
        temp = random.choice(tile_list)
        y_cor = tile_list.index(temp)
        x_cor = random.choice(temp)
        return (x_cor, y_cor)


class Tile:
    """
    distribute the various characters and items into the different tiles in the level
    tile_list --> list generated by level class
    monster_list --> list generated by monster class(tbc)
    item_list --> list generated by item lclass(tbc)
    
    """
    def __init__(self, tile_list, monster_list, item_list):
        self.tile_list = tile_list
        self.monster_list = monster_list
        self.item_list = item_list


        
            

    def add_items(self, data):
        """
       randomly add items into tiles
       """
        pass

    def display(self, tile_number):
        print()