import random

class Level:
    """
    generate new level by the size given
    level_num --> int
    """
    def __init__(self, tile_list, level_num, monsters_list, items_list):
        self.tile_list = tile_list
        self.level_num = level_num
        self.monsters_list = monsters_list
        self.items_list = items_list
    
    def get_levelnumber(self):
        """
        print the level number
        """
        print(self.level_num)

    def get_floorplan(self):
        """
        return the level generated
        """
        return self.tile_list

    def spawn_monsters(self):
        """
        randomly add monsters into tiles
        """
        for i in range(len(self.monsters_list)):
            new_tile = random.choice(self.tile_list)
            if new_tile.get_monster() is None:
                self.monsters_list[i].position = new_tile.position
            else:
                i -= 1
                
    def spawn_items(self):
        """
        randomly add items into tiles
        """
        for i in range(len(self.items_list)):
            new_tile = random.choice(self.tile_list)
            if new_tile.get_item() is None:
                self.items_list[i].position = new_tile.position
            else:
                i -= 1


                
                
    


class Tile:
    """
    distribute the various characters and items into the different tiles in the level
    tile_list --> list generated by level class
    monster_list --> list generated by monster class(tbc)
    item_list --> list generated by item lclass(tbc)
    
    """
    def __init__(self, position, monster, item):
        self.position = position
        self.monster = monster
        self.item = item


    def get_item(self):
        return self.item

    def get_monster(self):
        return self.monster

    

    def display(self):
        print()