import data
test = data.Colours()
# print(test.colourised(test.BLINK, 'testing'))

# colour = ['BLACK', 'RED', 'GREEN', 'BROWN', 'BLUE', 'PURPLE', 'CYAN', 'LIGHT_GRAY', 'DARK_GRAY', 'LIGHT_RED', 'LIGHT_GREEN', 'YELLOW', 'LIGHT_BLUE', 'LIGHT_CYAN', 'LIGHT_WHITE', 'PURPLE', 'BOLD', 'FAINT', 'ITALIC', 'UNDERLINE', 'BLINK', 'NEGATIVE', 'CROSSED', 'END' ]

print(test.colourised(test.BLACK, 'hi'))
print(test.colourised(test.RED, 'hi'))
print(test.colourised(test.GREEN, 'hi'))
print(test.colourised(test.BROWN, 'hi'))
#print(test.colourised(test.BLUE, 'hi'))
#print(test.colourised(test.PURPLE, 'hi'))
#print(test.colourised(test.CYAN, 'hi'))
print(test.colourised(test.LIGHT_GRAY, 'hi'))
print(test.colourised(test.DARK_GRAY, 'hi'))
print(test.colourised(test.LIGHT_RED, 'hi'))
print(test.colourised(test.LIGHT_GREEN, 'hi'))
print(test.colourised(test.YELLOW, 'hi'))
#print(test.colourised(test.LIGHT_BLUE, 'hi'))
#print(test.colourised(test.LIGHT_CYAN, 'hi'))
print(test.colourised(test.LIGHT_WHITE, 'hi'))
print(test.colourised(test.BOLD, 'hi'))
print(test.colourised(test.FAINT, 'hi'))
print(test.colourised(test.ITALIC, 'hi'))
print(test.colourised(test.UNDERLINE, 'hi'))
print(test.colourised(test.BLINK, 'hi'))
print(test.colourised(test.NEGATIVE, 'hi'))
print(test.colourised(test.CROSSED, 'hi'))
print(test.colourised(test.END, 'hi'))
